on:
  release:
    types: [created]

name: Create Release

jobs:
  tagged-release:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install modules
      run: npm i

    - name: Build plugin
      run: npm run build

    - name: Rename build folder 
      run: mv build ${{ github.event.repository.name }}
    
    - name: Zip build
      uses: montudor/action-zip@v1
      with:
        args: zip -qq -r ${{ github.event.repository.name }}.zip ${{ github.event.repository.name }}

    - name: Get release
      id: get_release
      uses: bruceadams/get-release@v1.2.3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.github_token }}
      with:
        upload_url: ${{ steps.get_release.outputs.upload_url }}
        asset_path: ./${{ github.event.repository.name }}.zip
        asset_name: ${{ github.event.repository.name }}.zip
        asset_content_type: application/zip

    - name: update release
      id: update_release
      uses: tubone24/update_release@v1.0
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        prerelease: false

    # - name: Create latest release 
    #   uses: marvinpinto/action-automatic-releases@latest
    #   with:
    #     automatic_release_tag: "latest"
    #     repo_token: "${{ secrets.GITHUB_TOKEN }}"
    #     prerelease: false
    #     files: build.zip
