on:
  release:
    types: [created]

name: Create Release

jobs:
  tagged-release:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install modules
      run: npm i

    - name: Build plugin
      run: npm run build

    - name: Rename build folder 
      run: mv build ${{ github.event.repository.name }}
    
    - name: 7z build
      uses: edgarrc/action-7z@v1
      with:
        args: 7z a -t7z -mx=9 ${{ github.event.repository.name }}.7z ${{ github.event.repository.name }}

    - name: Get release
      id: get_release
      uses: bruceadams/get-release@v1.2.3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.github_token }}
      with:
        upload_url: ${{ steps.get_release.outputs.upload_url }}
        asset_path: ./${{ github.event.repository.name }}.7z
        asset_name: ${{ github.event.repository.name }}.7z
        asset_content_type: application/zip
